APP:
  NAME: gosari
  MODE: development
  ADDR: :3000
  URL: http://localhost:3000
  KEY: Cbt3AUS3Pl9nK2p1lAHNGPZZQSaJWNLijxR42qRgq0iBb5

DB:
  MASTER:
    CONNECTION: mysql
    HOST: 127.0.0.1
    PORT: 3306
    DATABASE: gosari
    USERNAME: root
    PASSWORD: top_secret

REDIS:
  ADDR:
  PASSWORD:
  DATABASE:

LOG:
  FOLDER:
  PREFIX:
  MAXSIZE:
  MAXAGES:
